### ISSUE TITLE
Patch mockdata

### ISSUE THREAD

**Issue by axellorreyne** [SELab-2/UGent-1#143]
```[tasklist]
### Tasks
- [x] Make some courses open and some closed
- [x] Set default passwords for mock users for development/testing
- [x] Make mock teacher and admin accounts
```
