### ISSUE TITLE
Frontend bugs

### ISSUE THREAD

**Issue by robinpdev** [SELab-2/UGent-1#154]
```[tasklist]
### Tasks
- [x] submission -> project pagina navigatie geeft undefined id in url
- [x] profile edit -> error in put request als profile picture wordt aangepast
- [x] you can submit on projects for which the submission date is expired
- [x] submission download button crashes
- [ ] user loses courses when switching roles
```

```[tasklist]
### Tasks
- [ ] dropzone voor files bij submission
```

**Comment by robinpdev** [comment]
Profile picture bug is not on my machine, but is on production, nee to investigate further
